packages:
  - "packages/*"
  - "services/*"
  - "apps/*"

allowBuilds:
  esbuild: true
  "@prisma/engines": true
  prisma: true
  "@nestjs/core": true
  sharp: true
  "@tailwindcss/oxide": true
  '@prisma/client': true
  '@scarf/scarf': false
